2021-05-19 20:10:45,518 INFO    MainThread:535427 [internal.py:wandb_internal():91] W&B internal server running at pid: 535427, started at: 2021-05-19 20:10:45.518557
2021-05-19 20:10:45,520 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: check_version
2021-05-19 20:10:45,520 INFO    WriterThread:535427 [datastore.py:open_for_write():77] open: /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/Regression/house-price-preds/wandb/run-20210519_201040-c3tc458l/run-c3tc458l.wandb
2021-05-19 20:10:45,522 DEBUG   SenderThread:535427 [sender.py:send():176] send: header
2021-05-19 20:10:45,522 DEBUG   SenderThread:535427 [sender.py:send_request():186] send_request: check_version
2021-05-19 20:10:46,402 DEBUG   SenderThread:535427 [sender.py:send():176] send: run
2021-05-19 20:10:46,404 DEBUG   SenderThread:535427 [git.py:repo():33] git repository is invalid
2021-05-19 20:10:46,927 INFO    SenderThread:535427 [dir_watcher.py:__init__():168] watching files in: /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/Regression/house-price-preds/wandb/run-20210519_201040-c3tc458l/files
2021-05-19 20:10:46,927 INFO    SenderThread:535427 [sender.py:_start_run_threads():699] run started: c3tc458l with start time 1621435245
2021-05-19 20:10:46,927 DEBUG   SenderThread:535427 [sender.py:send():176] send: summary
2021-05-19 20:10:46,928 INFO    SenderThread:535427 [sender.py:_save_file():821] saving file wandb-summary.json with policy end
2021-05-19 20:10:46,928 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: run_start
2021-05-19 20:10:47,929 INFO    Thread-8  :535427 [dir_watcher.py:_on_file_created():216] file/dir created: /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/Regression/house-price-preds/wandb/run-20210519_201040-c3tc458l/files/wandb-summary.json
2021-05-19 20:10:47,947 DEBUG   HandlerThread:535427 [meta.py:__init__():39] meta init
2021-05-19 20:10:47,947 DEBUG   HandlerThread:535427 [meta.py:__init__():53] meta init done
2021-05-19 20:10:47,947 DEBUG   HandlerThread:535427 [meta.py:probe():210] probe
2021-05-19 20:10:47,953 DEBUG   HandlerThread:535427 [git.py:repo():33] git repository is invalid
2021-05-19 20:10:47,953 DEBUG   HandlerThread:535427 [meta.py:_save_code():89] save code
2021-05-19 20:10:47,953 WARNING HandlerThread:535427 [meta.py:_save_code():91] unable to save code -- program entry not found
2021-05-19 20:10:47,953 DEBUG   HandlerThread:535427 [meta.py:_save_pip():57] save pip
2021-05-19 20:10:47,953 DEBUG   HandlerThread:535427 [meta.py:_save_pip():71] save pip done
2021-05-19 20:10:47,953 DEBUG   HandlerThread:535427 [meta.py:_save_conda():78] save conda
2021-05-19 20:10:48,930 INFO    Thread-8  :535427 [dir_watcher.py:_on_file_created():216] file/dir created: /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/Regression/house-price-preds/wandb/run-20210519_201040-c3tc458l/files/conda-environment.yaml
2021-05-19 20:10:48,931 INFO    Thread-8  :535427 [dir_watcher.py:_on_file_created():216] file/dir created: /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/Regression/house-price-preds/wandb/run-20210519_201040-c3tc458l/files/requirements.txt
2021-05-19 20:10:52,301 DEBUG   HandlerThread:535427 [meta.py:_save_conda():86] save conda done
2021-05-19 20:10:52,302 DEBUG   HandlerThread:535427 [meta.py:probe():252] probe done
2021-05-19 20:10:52,304 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: stop_status
2021-05-19 20:10:52,304 DEBUG   SenderThread:535427 [sender.py:send_request():186] send_request: stop_status
2021-05-19 20:10:52,557 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: log_artifact
2021-05-19 20:10:52,559 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: pause
2021-05-19 20:10:52,559 INFO    HandlerThread:535427 [handler.py:handle_request_pause():519] stopping system metrics thread
2021-05-19 20:10:52,929 INFO    Thread-8  :535427 [dir_watcher.py:_on_file_modified():229] file/dir modified: /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/Regression/house-price-preds/wandb/run-20210519_201040-c3tc458l/files/conda-environment.yaml
2021-05-19 20:10:52,929 INFO    Thread-8  :535427 [dir_watcher.py:_on_file_created():216] file/dir created: /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/Regression/house-price-preds/wandb/run-20210519_201040-c3tc458l/files/output.log
2021-05-19 20:10:52,930 INFO    Thread-8  :535427 [dir_watcher.py:_on_file_created():216] file/dir created: /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/Regression/house-price-preds/wandb/run-20210519_201040-c3tc458l/files/wandb-metadata.json
2021-05-19 20:10:53,013 DEBUG   SenderThread:535427 [sender.py:send():176] send: files
2021-05-19 20:10:53,013 INFO    SenderThread:535427 [sender.py:_save_file():821] saving file wandb-metadata.json with policy now
2021-05-19 20:10:53,014 DEBUG   SenderThread:535427 [sender.py:send_request():186] send_request: log_artifact
2021-05-19 20:10:54,389 INFO    Thread-11 :535427 [upload_job.py:push():133] Uploaded file /tmp/tmpu_ybc6rywandb/829nsita-wandb-metadata.json
2021-05-19 20:10:56,389 INFO    Thread-13 :535427 [upload_job.py:push():91] Uploaded file /home/indika/.cache/wandb/artifacts/obj/md5/a2/5aea3e68c8798927b2032992be9597
2021-05-19 20:10:58,652 DEBUG   SenderThread:535427 [sender.py:send():176] send: stats
2021-05-19 20:11:08,014 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: stop_status
2021-05-19 20:11:08,015 DEBUG   SenderThread:535427 [sender.py:send_request():186] send_request: stop_status
2021-05-19 20:11:15,343 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: resume
2021-05-19 20:11:15,343 INFO    HandlerThread:535427 [handler.py:handle_request_resume():514] starting system metrics thread
2021-05-19 20:11:16,054 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: log_artifact
2021-05-19 20:11:16,055 DEBUG   SenderThread:535427 [sender.py:send_request():186] send_request: log_artifact
2021-05-19 20:11:16,060 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: pause
2021-05-19 20:11:16,060 INFO    HandlerThread:535427 [handler.py:handle_request_pause():519] stopping system metrics thread
2021-05-19 20:11:16,073 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: resume
2021-05-19 20:11:16,073 INFO    HandlerThread:535427 [handler.py:handle_request_resume():514] starting system metrics thread
2021-05-19 20:11:16,790 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: log_artifact
2021-05-19 20:11:16,793 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: pause
2021-05-19 20:11:16,793 INFO    HandlerThread:535427 [handler.py:handle_request_pause():519] stopping system metrics thread
2021-05-19 20:11:16,898 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: resume
2021-05-19 20:11:16,898 INFO    HandlerThread:535427 [handler.py:handle_request_resume():514] starting system metrics thread
2021-05-19 20:11:17,520 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: log_artifact
2021-05-19 20:11:17,523 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: pause
2021-05-19 20:11:17,523 INFO    HandlerThread:535427 [handler.py:handle_request_pause():519] stopping system metrics thread
2021-05-19 20:11:17,622 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: resume
2021-05-19 20:11:17,622 INFO    HandlerThread:535427 [handler.py:handle_request_resume():514] starting system metrics thread
2021-05-19 20:11:18,527 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: log_artifact
2021-05-19 20:11:18,529 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: pause
2021-05-19 20:11:18,529 INFO    HandlerThread:535427 [handler.py:handle_request_pause():519] stopping system metrics thread
2021-05-19 20:11:18,545 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: resume
2021-05-19 20:11:18,546 INFO    HandlerThread:535427 [handler.py:handle_request_resume():514] starting system metrics thread
2021-05-19 20:11:18,937 INFO    Thread-8  :535427 [dir_watcher.py:_on_file_created():216] file/dir created: /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/Regression/house-price-preds/wandb/run-20210519_201040-c3tc458l/files/code/_session_history.ipynb
2021-05-19 20:11:18,938 INFO    Thread-8  :535427 [dir_watcher.py:_on_file_created():216] file/dir created: /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/Regression/house-price-preds/wandb/run-20210519_201040-c3tc458l/files/code
2021-05-19 20:11:19,145 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: log_artifact
2021-05-19 20:11:19,150 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: poll_exit
2021-05-19 20:11:19,938 INFO    Thread-8  :535427 [dir_watcher.py:_on_file_modified():229] file/dir modified: /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/Regression/house-price-preds/wandb/run-20210519_201040-c3tc458l/files/output.log
2021-05-19 20:11:20,123 INFO    Thread-18 :535427 [upload_job.py:push():91] Uploaded file /home/indika/.cache/wandb/artifacts/obj/md5/eb/14da77f9940cef9433ad0d5d55445a
2021-05-19 20:11:23,808 DEBUG   SenderThread:535427 [sender.py:send():176] send: stats
2021-05-19 20:11:23,809 DEBUG   SenderThread:535427 [sender.py:send_request():186] send_request: log_artifact
2021-05-19 20:11:24,251 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: poll_exit
2021-05-19 20:11:24,389 ERROR   FileStreamThread:535427 [file_stream.py:_thread_except_body():286] generic exception in filestream thread
Traceback (most recent call last):
  File "/home/indika/anaconda3/lib/python3.7/site-packages/wandb/sdk/internal/file_stream.py", line 282, in _thread_except_body
    self._thread_body()
  File "/home/indika/anaconda3/lib/python3.7/site-packages/wandb/sdk/internal/file_stream.py", line 260, in _thread_body
    self._send(ready_chunks)
  File "/home/indika/anaconda3/lib/python3.7/site-packages/wandb/sdk/internal/file_stream.py", line 327, in _send
    retry_callback=self._api.retry_callback,
  File "/home/indika/anaconda3/lib/python3.7/site-packages/wandb/sdk/internal/file_stream.py", line 295, in _handle_response
    raise response
  File "/home/indika/anaconda3/lib/python3.7/site-packages/wandb/sdk/internal/file_stream.py", line 382, in request_with_retry
    response.raise_for_status()
  File "/home/indika/anaconda3/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/files/ranuga-d/House-Price-Pred/c3tc458l/file_stream
2021-05-19 20:11:24,751 ERROR   SenderThread:535427 [internal_api.py:execute():130] 404 response executing GraphQL.
2021-05-19 20:11:24,752 ERROR   SenderThread:535427 [internal_api.py:execute():131] {"errors":[{"message":"failed to find run House-Price-Pred/c3tc458l","path":["createArtifact"]}],"data":{"createArtifact":null}}
2021-05-19 20:11:24,752 DEBUG   SenderThread:535427 [sender.py:send():176] send: stats
2021-05-19 20:11:24,753 DEBUG   SenderThread:535427 [sender.py:send_request():186] send_request: log_artifact
2021-05-19 20:11:25,498 ERROR   SenderThread:535427 [internal_api.py:execute():130] 404 response executing GraphQL.
2021-05-19 20:11:25,498 ERROR   SenderThread:535427 [internal_api.py:execute():131] {"errors":[{"message":"failed to find run House-Price-Pred/c3tc458l","path":["createArtifact"]}],"data":{"createArtifact":null}}
2021-05-19 20:11:25,498 DEBUG   SenderThread:535427 [sender.py:send():176] send: stats
2021-05-19 20:11:25,499 DEBUG   SenderThread:535427 [sender.py:send_request():186] send_request: log_artifact
2021-05-19 20:11:26,155 ERROR   SenderThread:535427 [internal_api.py:execute():130] 404 response executing GraphQL.
2021-05-19 20:11:26,155 ERROR   SenderThread:535427 [internal_api.py:execute():131] {"errors":[{"message":"failed to find run House-Price-Pred/c3tc458l","path":["createArtifact"]}],"data":{"createArtifact":null}}
2021-05-19 20:11:26,156 DEBUG   SenderThread:535427 [sender.py:send():176] send: stats
2021-05-19 20:11:26,156 DEBUG   SenderThread:535427 [sender.py:send():176] send: config
2021-05-19 20:11:26,156 DEBUG   SenderThread:535427 [sender.py:send_request():186] send_request: log_artifact
2021-05-19 20:11:26,659 ERROR   SenderThread:535427 [internal_api.py:execute():130] 404 response executing GraphQL.
2021-05-19 20:11:26,660 ERROR   SenderThread:535427 [internal_api.py:execute():131] {"errors":[{"message":"failed to find run House-Price-Pred/c3tc458l","path":["createArtifact"]}],"data":{"createArtifact":null}}
2021-05-19 20:11:27,283 ERROR   SenderThread:535427 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-05-19 20:11:27,283 ERROR   SenderThread:535427 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '317286-c3tc458l' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-05-19 20:11:29,088 ERROR   SenderThread:535427 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-05-19 20:11:29,088 ERROR   SenderThread:535427 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '317286-c3tc458l' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-05-19 20:11:29,351 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: poll_exit
2021-05-19 20:11:32,254 ERROR   SenderThread:535427 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-05-19 20:11:32,254 ERROR   SenderThread:535427 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '317286-c3tc458l' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-05-19 20:11:32,254 ERROR   SenderThread:535427 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "/home/indika/anaconda3/lib/python3.7/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/indika/anaconda3/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 133, in execute
    six.reraise(*sys.exc_info())
  File "/home/indika/anaconda3/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/indika/anaconda3/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 127, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/indika/anaconda3/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/indika/anaconda3/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/indika/anaconda3/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/home/indika/anaconda3/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2021-05-19 20:11:34,452 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: poll_exit
2021-05-19 20:11:38,037 ERROR   SenderThread:535427 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-05-19 20:11:38,038 ERROR   SenderThread:535427 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '317286-c3tc458l' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-05-19 20:11:39,553 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: poll_exit
2021-05-19 20:11:44,653 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: poll_exit
2021-05-19 20:11:47,642 ERROR   SenderThread:535427 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-05-19 20:11:47,643 ERROR   SenderThread:535427 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '317286-c3tc458l' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-05-19 20:11:49,754 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: poll_exit
2021-05-19 20:11:54,855 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: poll_exit
2021-05-19 20:11:59,955 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: poll_exit
2021-05-19 20:12:04,405 ERROR   SenderThread:535427 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-05-19 20:12:04,405 ERROR   SenderThread:535427 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '317286-c3tc458l' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-05-19 20:12:05,056 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: poll_exit
2021-05-19 20:12:10,157 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: poll_exit
2021-05-19 20:12:15,257 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: poll_exit
2021-05-19 20:12:20,358 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: poll_exit
2021-05-19 20:12:25,459 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: poll_exit
2021-05-19 20:12:30,559 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: poll_exit
2021-05-19 20:12:35,660 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: poll_exit
2021-05-19 20:12:40,761 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: poll_exit
2021-05-19 20:12:44,350 ERROR   SenderThread:535427 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-05-19 20:12:44,351 ERROR   SenderThread:535427 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '317286-c3tc458l' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-05-19 20:12:45,862 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: poll_exit
2021-05-19 20:12:50,962 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: poll_exit
2021-05-19 20:12:56,063 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: poll_exit
2021-05-19 20:13:01,163 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: poll_exit
2021-05-19 20:13:06,264 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: poll_exit
2021-05-19 20:13:11,365 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: poll_exit
2021-05-19 20:13:16,466 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: poll_exit
2021-05-19 20:13:21,567 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: poll_exit
2021-05-19 20:13:26,667 DEBUG   HandlerThread:535427 [handler.py:handle_request():121] handle_request: poll_exit
